### ISSUE TITLE
A little credit?

### ISSUE THREAD

**Issue by nyvorin** [pychen0918/bad-words-chinese#1]
I'm flattered that you found my work useful. While i understand everything is open-source and all and I personally believe in any useful contribution, you should at least pay a little attribution to the original authors work. https://github.com/web-mech/badwords. Thanks.

**Comment by pychen0918** [comment]
Hi web-mech,
Sorry for late response. I have updated the description with the credit information on Github and npm.
Please let me know if you have any suggestion or comment on it, thank you.

**Comment by mindfulmike** [comment]
Thank you! Very much appreciated.

**Comment by nyvorin** [comment]
Thank you! Very much appreciated!
